### ISSUE TITLE
Can you explicitly share the code/dockerfile that produces openpolicyagent/opa:0.10.7-envoy

### ISSUE THREAD

**Issue by danielpops** [ashutosh-narkar/opa-envoy-ext-authz#1]
The `docker-compose.yaml` file references `openpolicyagent/opa:0.10.7-envoy`; Can you share the code/dockerfile/build setup that produces that? Is it basically just the `go` code from https://github.com/open-policy-agent/opa-istio-plugin?

Thanks!

**Comment by ashutosh-narkar** [comment]
Yes. I have re-tagged the `openpolicyagent/opa:0.10.7-istio-2`.
